---
title: "mp3"
author: "Sunnie Ning and Ayumi Mizuno"
date: "November 13, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(mdsr)
library(dplyr)
library(RMySQL)

db <- dbConnect_scidb(dbname="imdb")
```


```{r}
sql_sequels <- db %>%
  dbGetQuery("SELECT DISTINCT(t.id), t.title AS movie, t.production_year, t2.id, t2.title AS sequel_movie, t2.production_year
FROM movie_companies mc
JOIN company_name cn ON mc.company_id = cn.id
JOIN title t ON mc.movie_id = t.id
JOIN movie_link ml ON ml.movie_id = t.id
JOIN title t2 ON ml.linked_movie_id = t2.id
JOIN movie_info mi ON t.id = mi.movie_id
WHERE cn.country_code = '[us]' 
AND t.kind_id = 1 
AND ml.link_type_id = 2 
AND mi.info_type_id IN(4,8)
AND mi.info IN('USA', 'English')")
```
#save sequel database to a file
#load("sequels.Rda") to use
```{r}
save(sql_sequels, file="sequels.Rda")
```

```{r}
sql_remade <- db %>%
  dbGetQuery("SELECT DISTINCT(t.id), t.title AS movie, t.production_year, t2.id, t2.title AS remake_movie, t2.production_year
FROM movie_companies mc
JOIN company_name cn ON mc.company_id = cn.id
JOIN title t ON mc.movie_id = t.id
JOIN movie_link ml ON ml.movie_id = t.id
JOIN title t2 ON ml.linked_movie_id = t2.id
JOIN movie_info mi ON t.id = mi.movie_id
WHERE cn.country_code = '[us]' 
AND t.kind_id = 1 
AND ml.link_type_id = 4 
AND mi.info_type_id IN(4,8)
AND mi.info IN('USA', 'English')")

```
```{r}
save(sql_remade, file="remakes.Rda")
```
```{r}
sql_reboot <- db %>%
  dbGetQuery("SELECT DISTINCT(t.id), t.title AS movie, t.production_year, t2.id, t2.title AS reboot_movie, t2.production_year
FROM movie_companies mc
JOIN company_name cn ON mc.company_id = cn.id
JOIN title t ON mc.movie_id = t.id
JOIN movie_link ml ON ml.movie_id = t.id
JOIN title t2 ON ml.linked_movie_id = t2.id
JOIN movie_info mi ON t.id = mi.movie_id
WHERE cn.country_code = '[us]' 
AND t.kind_id = 1 
AND ml.link_type_id = 13 
AND mi.info_type_id IN(4,8)
AND mi.info IN('USA', 'English')")

```
```{r}
save(sql_reboot, file="reboot.Rda")
```
